# Generated by Django 6.0.5 on 2026-05-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('poste', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipe/')),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('entreprise', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('service_souhaite', models.CharField(blank=True, choices=[('web', 'Développement Web'), ('mobile', 'Application Mobile'), ('design', 'Design UI/UX'), ('marketing', 'Marketing Digital'), ('conseil', 'Conseil & Stratégie'), ('autre', 'Autre')], max_length=20)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('repondu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('client', models.CharField(max_length=100)),
                ('categorie', models.CharField(blank=True, help_text='Ex: Développement Web', max_length=100)),
                ('description', models.TextField()),
                ('technologies', models.CharField(help_text='Séparées par virgule: React, Python', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/')),
                ('lien', models.URLField(blank=True)),
                ('date_realisation', models.DateField()),
                ('en_vedette', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_realisation'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('description_courte', models.CharField(max_length=200, verbose_name='Description courte')),
                ('description_longue', models.TextField(verbose_name='Description complète')),
                ('fonctionnalites', models.TextField(blank=True, help_text='Une fonctionnalité par ligne')),
                ('icone', models.CharField(default='fa-star', help_text='Classe FontAwesome (ex: fa-code)', max_length=50)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(default='MonEntreprise', max_length=100)),
                ('slogan', models.CharField(default='Solutions innovantes pour votre entreprise', max_length=200)),
                ('adresse', models.TextField(default="123 Rue de l'Innovation, 75001 Paris")),
                ('telephone', models.CharField(default='+33 1 23 45 67 89', max_length=30)),
                ('email_contact', models.EmailField(default='contact@monentreprise.fr', max_length=254)),
                ('email_support', models.EmailField(blank=True, max_length=254)),
                ('horaires', models.TextField(default='Lun-Ven : 9h00 - 18h00\nSamedi : 10h00 - 13h00')),
                ('url_linkedin', models.URLField(blank=True)),
                ('url_twitter', models.URLField(blank=True)),
                ('url_facebook', models.URLField(blank=True)),
                ('url_instagram', models.URLField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('poste_client', models.CharField(max_length=100)),
                ('entreprise_client', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('note', models.PositiveIntegerField(choices=[(1, '1★'), (2, '2★'), (3, '3★'), (4, '4★'), (5, '5★')], default=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='temoignages/')),
                ('approuve', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('accueil', 'Accueil'), ('a_propos', 'À propos'), ('services', 'Services'), ('portfolio', 'Portfolio'), ('equipe', 'Équipe'), ('contact', 'Contact'), ('global', 'Global')], max_length=20)),
                ('cle', models.SlugField(help_text='Ex: hero_titre')),
                ('type', models.CharField(choices=[('text', 'Texte court'), ('textarea', 'Texte long'), ('html', 'HTML riche')], default='text', max_length=10)),
                ('label', models.CharField(help_text="Description lisible pour l'admin", max_length=100)),
                ('valeur', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bloc de contenu',
                'verbose_name_plural': 'Blocs de contenu',
                'ordering': ['page', 'cle'],
                'unique_together': {('page', 'cle')},
            },
        ),
    ]
